includes:
        - base.yaml
        - model.yaml
        - policy_trainer.yaml

load: ${load}
top_p: 0.9
parallel_output: True
tensor_model_parallel_size: ${ref_tensor_model_parallel_size:2}
pipeline_model_parallel_size: ${ref_pp:1}

sequence_parallel: True
use_dynamic_collate: ${use_dynamic_collate:False}
